# Generated by Django 4.2.13 on 2024-07-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_extra_images_extra_images_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extra_images',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='extra_images',
            field=models.ManyToManyField(to='blog.extra_images'),
        ),
    ]
